#!/usr/bin/env python3
"""Generate one share card per property: p/<id>.html + assets/og/<id>.jpg.

WHY THIS EXISTS
---------------
WhatsApp, iMessage, Slack and Facebook read Open Graph tags out of the STATIC
html at the shared URL. They do not run JavaScript. Every property on this site
is fetched client-side from data/lumina-demo-leads.json, so a link to
`listings.html?property=lumina-016` handed the crawler listings.html's own
fixed og:image — the generic villa — no matter which property was meant. A
query string cannot change static html, and there is no server to change it on
(GitHub Pages / Cloudflare, both static).

So each property gets a real file with its own tags baked in. The crawler reads
the tags; a human's browser runs js/share-card.js and is replaced onto the real
destination before it paints. Nothing about where a shared link LANDS changes.

REGENERATE THIS whenever data/lumina-demo-leads.json changes:

    python scripts/build-share-cards.py

It is idempotent, and it deletes cards for records that no longer exist — a
share card outliving its property is a link to a photograph of something that
is no longer for sale.

Not a build step in the CI sense: the output is committed, exactly like the
area and insight pages. Nothing on the site depends on this script at runtime.
"""

import json
import pathlib
import shutil
import sys

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
HOST = 'https://www.lumina-jo.com'
DATA = ROOT / 'data' / 'lumina-demo-leads.json'
CARDS = ROOT / 'p'
OGDIR = ROOT / 'assets' / 'og'

# 1200x630 is the only safe target. WhatsApp downgrades anything roughly square
# or portrait to a small thumbnail card instead of the big one, and it gives up
# on large files — 54 of the 118 cover photos are over 300KB as shot, which is
# where its previews start failing. At q82 this lands around 120KB.
OG_W, OG_H, OG_Q = 1200, 630, 82


def text(v):
    return '' if v is None else str(v).strip()


def esc(v):
    """Attribute-safe. Meta content is an attribute, so quotes matter."""
    return (text(v).replace('&', '&amp;').replace('<', '&lt;')
            .replace('>', '&gt;').replace('"', '&quot;'))


def format_price(rec):
    """Mirrors Lumina.formatPrice in js/property-card.js — deliberately.

    If these two ever disagree, a card promises a price the page does not show.
    The rules are not arbitrary: needs_price_review marks five rents that may be
    monthly among annual ones, and per_sqm marks rates quoted per square metre.
    Both withhold rather than guess. Do not 'simplify' either away here.
    """
    if rec.get('needs_price_review'):
        return 'Price on request'
    raw = rec.get('price_jod_test_margin')
    if raw is None:
        raw = rec.get('price_jod_raw')
    try:
        amount = float(raw)
    except (TypeError, ValueError):
        return 'Price on request'
    unit = ' JOD/m²' if rec.get('price_unit') == 'per_sqm' else ' JOD'
    tx = text(rec.get('transaction'))
    return f'{amount:,.0f}{unit}' + (f' · {tx}' if tx else '')


def describe(rec):
    bits = [text(rec.get('location_area')) or text(rec.get('location')) or 'Amman',
            format_price(rec)]
    n = rec.get('photo_count') or len(rec.get('images') or [])
    if n:
        bits.append(f'{n} photographs')
    return ' · '.join(b for b in bits if b)


def make_og_image(src_rel, dst):
    """Centre-crop the property's own cover to 1200x630.

    Cropping, not letterboxing: dark bars down both sides of a preview read as a
    broken image. The covers are already curated — six were hand-picked in the
    data so the card opens on the best room rather than whatever the
    photographer shot first — so the crop is the only judgement made here.
    """
    src = ROOT / text(src_rel).lstrip('/')
    if not src.exists():
        return False
    with Image.open(src) as im:
        im = im.convert('RGB')
        scale = max(OG_W / im.width, OG_H / im.height)
        im = im.resize((max(OG_W, round(im.width * scale)),
                        max(OG_H, round(im.height * scale))), Image.LANCZOS)
        left = (im.width - OG_W) // 2
        top = (im.height - OG_H) // 2
        dst.parent.mkdir(parents=True, exist_ok=True)
        # A new image, so no EXIF rides along into a published file.
        im.crop((left, top, left + OG_W, top + OG_H)).save(
            dst, 'JPEG', quality=OG_Q, optimize=True, progressive=True)
    return True


TEMPLATE = '''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — Lumina</title>
<meta name="description" content="{desc}">

<!-- GENERATED by scripts/build-share-cards.py — do not hand-edit, the next run
     overwrites it. Regenerate after any change to data/lumina-demo-leads.json.

     This page exists so a shared property link previews as that property. The
     crawler stops here and reads the tags below; a browser runs
     js/share-card.js and is replaced onto the real page before this paints.

     noindex, follow: {n} near-identical redirect pages are thin content and
     have no business in a search result. Preview crawlers do not consult it —
     it does not suppress the card. robots.txt must keep /p/ ALLOWED, or
     WhatsApp and Facebook cannot fetch this at all. -->
<meta name="robots" content="noindex, follow">

<meta property="og:type" content="article">
<meta property="og:site_name" content="Lumina">
<meta property="og:url" content="{host}/p/{id}.html">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<meta property="og:image" content="{host}/assets/og/{id}.jpg?v={ver}">
<meta property="og:image:secure_url" content="{host}/assets/og/{id}.jpg?v={ver}">
<meta property="og:image:type" content="image/jpeg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="{title}">
<meta property="og:locale" content="en_JO">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{title}">
<meta name="twitter:description" content="{desc}">
<meta name="twitter:image" content="{host}/assets/og/{id}.jpg?v={ver}">

<link rel="icon" href="../favicon.ico" sizes="32x32">
<link rel="icon" type="image/png" sizes="48x48" href="../assets/icon-48.png?v={ver}">
<link rel="apple-touch-icon" href="../assets/icon-180.png?v={ver}">
<style>
/* Inline rather than a stylesheet link: this page is replaced within a frame on
   any browser with JS, so a blocking request for css nobody sees is a request
   not worth making. It has to stand on its own without JS, though — hence real
   content below rather than a bare "redirecting…". */
*{{box-sizing:border-box}}
body{{margin:0;background:#06080C;color:#F4EFE6;
  font:400 16px/1.5 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;
  display:grid;place-items:center;min-height:100vh;padding:24px}}
.card{{width:min(560px,100%);background:#0D1219;border:1px solid rgba(255,178,90,.22);
  border-radius:16px;overflow:hidden}}
.card img{{display:block;width:100%;height:auto;aspect-ratio:1200/630;object-fit:cover}}
.body{{padding:20px 22px 24px}}
h1{{margin:0 0 6px;font-size:1.15rem;font-weight:600;line-height:1.35}}
p{{margin:0 0 18px;color:#9BA3AE;font-size:.9rem}}
a.go{{display:inline-block;padding:11px 20px;border-radius:999px;text-decoration:none;
  background:#FFB25A;color:#06080C;font-weight:600;font-size:.9rem}}
a.alt{{display:inline-block;margin-left:14px;color:#FFB25A;font-size:.9rem;
  text-decoration:none;border-bottom:1px solid rgba(255,178,90,.4)}}
a:focus-visible{{outline:2px solid #FFD7A3;outline-offset:3px}}
</style>
</head>
<body data-id="{id}" data-gallery="../listings.html?property={id}"
      data-details="../property-details.html?id={id}">
<noscript><meta http-equiv="refresh" content="0;url=../listings.html?property={id}"></noscript>
<div class="card">
  <img src="../assets/og/{id}.jpg?v={ver}" alt="{title}" width="1200" height="630">
  <div class="body">
    <h1>{title}</h1>
    <p>{desc}</p>
    <a class="go" href="../listings.html?property={id}">View this property</a>
    <a class="alt" href="../listings.html">All properties</a>
  </div>
</div>
<script src="../js/share-card.js?v={ver}"></script>
</body>
</html>
'''


def main():
    ver = sys.argv[1] if len(sys.argv) > 1 else '20260812'
    recs = json.loads(DATA.read_text(encoding='utf-8'))
    if isinstance(recs, dict):
        recs = next(v for v in recs.values() if isinstance(v, list))

    for d in (CARDS, OGDIR):
        d.mkdir(parents=True, exist_ok=True)

    live, no_cover = set(), []
    for rec in recs:
        pid = text(rec.get('id'))
        if not pid:
            continue
        live.add(pid)
        if not make_og_image(rec.get('image_url'), OGDIR / f'{pid}.jpg'):
            # Every record has had a photograph of its own since the 2026-08-05
            # clean-up, so this should stay empty. If it ever fires, the card is
            # written anyway and simply previews without a picture — which is
            # still better than previewing with another property's picture.
            no_cover.append(pid)
        (CARDS / f'{pid}.html').write_text(TEMPLATE.format(
            host=HOST, id=esc(pid), ver=esc(ver), n=len(recs),
            title=esc(rec.get('title') or 'Property'),
            desc=esc(describe(rec)),
        ), encoding='utf-8')

    stale = 0
    for d, suffix in ((CARDS, '.html'), (OGDIR, '.jpg')):
        for f in d.glob('*' + suffix):
            if f.stem not in live:
                f.unlink()
                stale += 1

    print(f'{len(live)} cards + og images written to p/ and assets/og/')
    if stale:
        print(f'{stale} stale file(s) removed')
    if no_cover:
        print('NO COVER PHOTO (card written without an image): ' + ', '.join(no_cover))


if __name__ == '__main__':
    main()
